name: AtherialCore
version: 1.0
main: me.TomAlex.Atherial.Main
author: eagleshooter-qroundhawk
description: AtherialCore
depend: [Vault]

commands:
    test:
        usage: /<command>
        description: Test Command.
    test2:
        usage: /<command>
        description: Test Command.
    money:
        usage: /<command>
        description: Money Command.
    addbank:
        usage: /<command>
        description: Addbank Command.
    setstorage:
        usage: /<command>
        description: Setstorage Command.
    addmarket:
        usage: /<command>
        description: Addmarket Command.
    respawnore:
        usage: /<command>
        description: Respawnore Command.
    spawnpickaxe:
        usage: /<command>
        description: Spawnpickaxe Command.
    repairsmith:
        usage: /<command>
        description: Spawns repairsmith.
    setchatprefix:
        usage: /<command>
        description: SetChatPrefix.
    prefixrefresh:
        usage: /<command>
        description: PrefixRefresh.    
    globalchat:
        usage: /<command>
        description: GlobalChat.
    staffchat:
        usage: /<command>
        aliases: sc
        description: StaffChat. 
    globalmarket:
        usage: /<command>
        aliases: sc
        description: Spawns market villager.
    itemdisenchanter:
        usage: /<command>
        aliases: sc
        description: Spawns disenchanter villager.
        
permissions:
    test.command:
        description: Test.
        default: op
    economy.money:
        description: Money.
        default: op
    economy.money.other:
        description: Money see.
        default: op
    economy.addbank:
        description: Addbank.
        default: op
    economy.setstorage:
        description: Addbank.
        default: op
    economy.addmarket:
        description: Addmarket.
        default: op
    mining.oresetup:
        description: Oresetup.
        default: op
    mining.respawnore:
        description: Respawnore.
        default: op
    mining.spawnpickaxe:
        description: Spawnpickaxe.
        default: op
    repairsmith.command:
        description: repairsmith.
        default: op
    globalmarket.command:
        description: globalmarket
        default: op
    itemdisenchanter.command:
        description: itemdisenchanter
        default: op        
    chat.staffcolor:
        description: Staff color.
        default: op
    chat.setchatprefix:
        description: SetChatPrefix.
        default: op
    chat.prefixrefresh:
        description: PrefixRefresh.
        default: op
    chat.globalchat:
        description: GlobalChat.
        default: op
    chat.staffchat:
        description: StaffChat.
        default: op
