name: AtherialCore
version: 0.1
main: me.TomAlex.Atherial.Main
author: eagleshooter-qroundhawk
description: AtherialCore
depend: [Vault]

commands:
    test:
        usage: /<command>
        description: Test Command.
    test2:
        usage: /<command>
        description: Test Command.
    money:
        usage: /<command>
        description: Money Command.
    addbank:
        usage: /<command>
        description: Addbank Command.
    setstorage:
        usage: /<command>
        description: Setstorage Command.
    addmarket:
        usage: /<command>
        description: Addmarket Command.
    respawnore:
        usage: /<command>
        description: Respawnore Command.
    spawnpickaxe:
        usage: /<command>
        description: Spawnpickaxe Command.
    repairsmith:
        usage: /<command>
        description: Spawns repairsmith.
        
permissions:
    test.command:
        description: Test.
        default: op
    economy.money:
        description: Money.
        default: op
    economy.money.other:
        description: Money see.
        default: op
    economy.addbank:
        description: Addbank.
        default: op
    economy.setstorage:
        description: Addbank.
        default: op
    economy.addmarket:
        description: Addmarket.
        default: op
    mining.oresetup:
        description: Oresetup.
        default: op
    mining.respawnore:
        description: Respawnore.
        default: op
    mining.spawnpickaxe:
        description: Spawnpickaxe.
        default: op
    repairsmith.command:
        description: repairsmith
        default: op